#theme: jekyll-theme-minimal
title: dd's homepage
author: dd
description: hello!

navbar-links:
  About Me: "aboutme"
  Resources:
    - Homepage: "https://dd9712.github.io/"
  Author's home: "https://dd9712.github.io/"




